name: Deploy to Render

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Trigger Render Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Deploy Backend via Render API
              run: |
                  curl -X POST https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys \
                    -H 'Accept: application/json' \
                    -H 'Authorization: Bearer ${{ secrets.RENDER_API_KEY }}' \
                    -d ''
