name: Deploy to Render

on:
    push:
        branches:
            - main

jobs:
    render-deploy:
        name: Trigger Render Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Deploy to Render
              uses: sws2apps/render-deploy@v1
              with:
                  service-id: ${{ secrets.RENDER_SERVICE_ID }}
                  api-key: ${{ secrets.RENDER_API_KEY }}
